### PR TITLE
Add Favicon

### PR DESCRIPTION
**Pull request by rachelcope**
Reason for Change
===================
* Add a new favicon
* https://trello.com/c/FPTtCQcy/91-favicon

Changes
=======
* I made the favicon with the initial "M" ("MB" was too small to see)

### CODE REVIEW

**Comment by rachelcope** [comment]
image

**Comment by jessieay** [comment]
(and by rebase and merge, I meant squash and merge)

**Comment by jayroh** [comment]
Looking good! :+1:

**Comment by rachelcope** [comment]
image

**Comment by alanjosephwilliams** [comment]
@rachelcope let's update the icon to be the primary color of the website (the sky blue)

**Pull request merged**
