### PR TITLE
Update secondary button color to light grey

### PR DESCRIPTION
**Pull request by rachelcope**
Reason for Change
===================
* Update secondary button color to be more prominent
* https://trello.com/c/o9pNcXDj/271-buttons-update-secondary-button-color

image

### CODE REVIEW

**Comment by rachelcope** [comment]
[[BUTTONS] Update secondary button color](https://trello.com/c/o9pNcXDj/271-buttons-update-secondary-button-color)

**Comment by adarsh** [comment]
Your change looks great!

Unrelated: should the copy for a button be "submit documents here"?  Like submit them in the button?

Since the other one is "I'll do this later" I wonder if the blue one should be "I'll do this now" or "Submit Documents Now"?

**Comment by rachelcope** [comment]
@adarsh I like your idea of changing it to "Submit documents now". Seems more clear. I'll update

**Comment by alanjosephwilliams** [comment]
👍

**Comment by danielladevera** [comment]
👍 from me too!

**Pull request merged**
