### PR TITLE
Frontend audit with Alan

### PR DESCRIPTION
**Pull request by jessieay**
* Update HTML to use classes that exist in our CSS
* Override / add classes where necessary
* Other small UI tweaks

### CODE REVIEW

**Comment by jessieay** [comment]
@adarsh I dont want to fix these CC issues just now, related to some jquery I copied over from GCF

**Comment by jessieay** [comment]
[Make "beta" banner less severe, using "teal"](https://trello.com/c/j5IvTHcj/173-make-beta-banner-less-severe-using-teal)

**Comment by zspencer** [comment]
I don't appear to have the rights to dismiss the codeclimate red x thing; but the concern it has doesn't really seem to be worth blocking this pull request.

**Comment by jessieay** [comment]
@zspencer thanks for taking a look!

making these changes made me realize that we should perhaps be using shared partials for this stuff, but all in due time!

**Pull request merged**
