### PR TITLE
Add setup for code climate test coverage

### PR DESCRIPTION
**Pull request by jessieay**

### CODE REVIEW

**Comment by jessieay** [comment]
[Add code climate](https://trello.com/c/p8O6c1q8/27-add-code-climate)

**Comment by jessieay** [comment]
Hey @loumoore could you help get this repo setup with code climate and code climate webhooks?

**Comment by jessieay** [comment]
@adarsh yeah I agree! Want to want on merging this until we have webhooks? I pinged Lou in the comment above to ask for that to be added

**Comment by adarsh** [comment]
@jessieay Nah, just merge and add the hooks in a separate PR. 🐑

**Comment by loumoore** [comment]
@jessieay should be all set up: https://codeclimate.com/github/codeforamerica/michigan-benefits

i also added the code climate repo token to the CircleCI env vars so you should start getting code coverage after future commits. you'll need to add a link to the badge in the readme if you want that too.

**Pull request merged**
