### PR TITLE
Remove filing form

### PR DESCRIPTION
**Pull request by jessieay**
**WHY**: Alan told me to

### CODE REVIEW

**Comment by jessieay** [comment]
[Remove Filing Form from 1171s we fax](https://trello.com/c/ZrCpE9Hw/238-remove-filing-form-from-1171s-we-fax)

**Comment by zspencer** [comment]
Approved, but I'm weirded out that CirlceCI didn't run

**Comment by jessieay** [comment]
@zspencer guessing it sees no difference between code because it's just the PDF change?

**Comment by jessieay** [comment]
Partially Degraded Service
https://status.circleci.com/

(for Github)

**Pull request merged**
