### PR TITLE
Add dual application homepage

### PR DESCRIPTION
**Pull request by rachelcope**
Changes
=======
* Add dual application homepage and copy.

fireshot capture 41 - michigan benefits - http___localhost_3000_dual-index

### CODE REVIEW

**Comment by jessieay** [comment]
tests are failing because you moved the `index` page to `dual_index` - assuming we want both, you'd want to make sure we preserve the existing static page that serves as a home page (and preserve that "bottom partial" as well)

**Comment by adarsh** [comment]
What do you think about renaming the files from `1f34e.png` to `apple.png` or similar? Same with the shield icon. Might be easier to fuzzy-find them.

**Comment by rachelcope** [comment]
@adarsh all the image files are named with the emojione code. I think I'll stick with to remain consistent

**Comment by adarsh** [comment]
@rachelcope makes sense, did not know about that code. Doesn't matter since it's in the `/emojis` directory. 👍

**Pull request merged**
